const books = [
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "A novel about the serious issues of rape and racial inequality, but told with warmth and humor.",
        publishedDate: new Date("1960-07-11"),
        genre: ["Fiction", "Classic"],
        rating: 4.9,
        coverImageUrl: "https://example.com/to-kill-a-mockingbird.jpg",
        isbn: "978-0061120084",
    },
    {
        title: "1984",
        author: "George Orwell",
        description: "A dystopian social science fiction novel and cautionary tale, warning of the dangers of totalitarianism.",
        publishedDate: new Date("1949-06-08"),
        genre: ["Dystopian", "Science Fiction"],
        rating: 4.8,
        coverImageUrl: "https://example.com/1984.jpg",
        isbn: "978-0451524935",
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        description: "A romantic novel that also critiques the British landed gentry at the end of the 18th century.",
        publishedDate: new Date("1813-01-28"),
        genre: ["Romance", "Classic"],
        rating: 4.7,
        coverImageUrl: "https://example.com/pride-and-prejudice.jpg",
        isbn: "978-1503290563",
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A novel set in the Roaring Twenties that critiques the American Dream through the life of Jay Gatsby.",
        publishedDate: new Date("1925-04-10"),
        genre: ["Fiction", "Classic"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-great-gatsby.jpg",
        isbn: "978-0743273565",
    },
    {
        title: "Moby Dick",
        author: "Herman Melville",
        description: "An epic tale of a sea captain's quest for revenge against a giant white whale.",
        publishedDate: new Date("1851-10-18"),
        genre: ["Adventure", "Classic"],
        rating: 4.2,
        coverImageUrl: "https://example.com/moby-dick.jpg",
        isbn: "978-1503280786",
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A story about a disenchanted teenager's experiences in New York City.",
        publishedDate: new Date("1951-07-16"),
        genre: ["Fiction", "Classic"],
        rating: 4.0,
        coverImageUrl: "https://example.com/the-catcher-in-the-rye.jpg",
        isbn: "978-0316769488",
    },
    {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        description: "A fantasy novel about a hobbit's adventure to reclaim treasure guarded by a dragon.",
        publishedDate: new Date("1937-09-21"),
        genre: ["Fantasy", "Adventure"],
        rating: 4.7,
        coverImageUrl: "https://example.com/the-hobbit.jpg",
        isbn: "978-0547928227",
    },
    {
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        description: "A novel about a young governess's struggles and romantic relationship with her employer.",
        publishedDate: new Date("1847-10-16"),
        genre: ["Romance", "Classic"],
        rating: 4.6,
        coverImageUrl: "https://example.com/jane-eyre.jpg",
        isbn: "978-0141441146",
    },
    {
        title: "Brave New World",
        author: "Aldous Huxley",
        description: "A dystopian novel exploring the impact of technological advancements on society.",
        publishedDate: new Date("1932-08-01"),
        genre: ["Dystopian", "Science Fiction"],
        rating: 4.3,
        coverImageUrl: "https://example.com/brave-new-world.jpg",
        isbn: "978-0060850524",
    },
    {
        title: "Fahrenheit 451",
        author: "Ray Bradbury",
        description: "A novel about a future society where books are banned and 'firemen' burn any that are found.",
        publishedDate: new Date("1953-10-19"),
        genre: ["Dystopian", "Science Fiction"],
        rating: 4.4,
        coverImageUrl: "https://example.com/fahrenheit-451.jpg",
        isbn: "978-1451673319",
    },
    {
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        description: "A high fantasy epic about the struggle to destroy a powerful ring and defeat the Dark Lord.",
        publishedDate: new Date("1954-07-29"),
        genre: ["Fantasy", "Adventure"],
        rating: 4.9,
        coverImageUrl: "https://example.com/the-lord-of-the-rings.jpg",
        isbn: "978-0544003415",
    },
    {
        title: "The Chronicles of Narnia",
        author: "C.S. Lewis",
        description: "A series of fantasy novels following the adventures of children in the magical land of Narnia.",
        publishedDate: new Date("1950-10-16"),
        genre: ["Fantasy", "Adventure"],
        rating: 4.8,
        coverImageUrl: "https://example.com/the-chronicles-of-narnia.jpg",
        isbn: "978-0066238500",
    },
    {
        title: "Little Women",
        author: "Louisa May Alcott",
        description: "A novel about the lives, loves, and tribulations of four sisters growing up in Civil War-era America.",
        publishedDate: new Date("1868-09-30"),
        genre: ["Fiction", "Classic"],
        rating: 4.5,
        coverImageUrl: "https://example.com/little-women.jpg",
        isbn: "978-0143039413",
    },
    {
        title: "The Alchemist",
        author: "Paulo Coelho",
        description: "A philosophical novel about a shepherd's journey to find a hidden treasure and his own personal legend.",
        publishedDate: new Date("1988-05-01"),
        genre: ["Adventure", "Philosophy"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-alchemist.jpg",
        isbn: "978-0062315007",
    },
    {
        title: "The Da Vinci Code",
        author: "Dan Brown",
        description: "A thriller involving a murder in the Louvre and a conspiracy related to the secret of the Holy Grail.",
        publishedDate: new Date("2003-03-18"),
        genre: ["Thriller", "Mystery"],
        rating: 4.3,
        coverImageUrl: "https://example.com/the-da-vinci-code.jpg",
        isbn: "978-0307474278",
    },
    {
        title: "Gone with the Wind",
        author: "Margaret Mitchell",
        description: "A historical novel set during the American Civil War and Reconstruction era, focusing on the life of Scarlett O'Hara.",
        publishedDate: new Date("1936-06-30"),
        genre: ["Historical", "Romance"],
        rating: 4.7,
        coverImageUrl: "https://example.com/gone-with-the-wind.jpg",
        isbn: "978-1451635629",
    },
    {
        title: "Catch-22",
        author: "Joseph Heller",
        description: "A satirical novel set during World War II, exploring the absurdities of war and bureaucracy.",
        publishedDate: new Date("1961-11-10"),
        genre: ["Satire", "War"],
        rating: 4.4,
        coverImageUrl: "https://example.com/catch-22.jpg",
        isbn: "978-1451626659",
    },
    {
        title: "The Shining",
        author: "Stephen King",
        description: "A horror novel about a family's terrifying experiences at an isolated hotel with a sinister past.",
        publishedDate: new Date("1977-01-28"),
        genre: ["Horror", "Thriller"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-shining.jpg",
        isbn: "978-0307743657",
    },
    {
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        description: "A comedic science fiction novel about the adventures of an unwitting human who hitchhikes through space.",
        publishedDate: new Date("1979-10-12"),
        genre: ["Science Fiction", "Comedy"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-hitchhikers-guide-to-the-galaxy.jpg",
        isbn: "978-0345391803",
    },
    {
        title: "One Hundred Years of Solitude",
        author: "Gabriel García Márquez",
        description: "A landmark novel of magical realism, detailing the multi-generational story of the Buendía family.",
        publishedDate: new Date("1967-05-30"),
        genre: ["Magical Realism", "Literary Fiction"],
        rating: 4.7,
        coverImageUrl: "https://example.com/one-hundred-years-of-solitude.jpg",
        isbn: "978-0060883287",
    },
    {
        title: "The Road",
        author: "Cormac McCarthy",
        description: "A post-apocalyptic novel about a father and son journeying across a desolate landscape.",
        publishedDate: new Date("2006-09-26"),
        genre: ["Post-Apocalyptic", "Drama"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-road.jpg",
        isbn: "978-0307387899",
    },
    {
        title: "The Girl with the Dragon Tattoo",
        author: "Stieg Larsson",
        description: "A thriller involving a journalist and a hacker investigating a disappearance from a wealthy family.",
        publishedDate: new Date("2005-08-01"),
        genre: ["Thriller", "Mystery"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-girl-with-the-dragon-tattoo.jpg",
        isbn: "978-0307454546",
    },
    {
        title: "The Little Prince",
        author: "Antoine de Saint-Exupéry",
        description: "A philosophical tale about a young prince who travels to different planets and learns about life and love.",
        publishedDate: new Date("1943-04-06"),
        genre: ["Fable", "Philosophy"],
        rating: 4.8,
        coverImageUrl: "https://example.com/the-little-prince.jpg",
        isbn: "978-0156012195",
    },
    {
        title: "The Martian",
        author: "Andy Weir",
        description: "A science fiction novel about an astronaut stranded on Mars and his struggle to survive.",
        publishedDate: new Date("2011-09-27"),
        genre: ["Science Fiction", "Adventure"],
        rating: 4.7,
        coverImageUrl: "https://example.com/the-martian.jpg",
        isbn: "978-0553418026",
    },
    {
        title: "The Hunger Games",
        author: "Suzanne Collins",
        description: "A dystopian novel about a televised survival competition in a future society.",
        publishedDate: new Date("2008-09-14"),
        genre: ["Dystopian", "Science Fiction"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-hunger-games.jpg",
        isbn: "978-0439023481",
    },
    {
        title: "The Outsiders",
        author: "S.E. Hinton",
        description: "A novel about the conflict between two teenage gangs in the 1960s.",
        publishedDate: new Date("1967-04-01"),
        genre: ["Fiction", "Young Adult"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-outsiders.jpg",
        isbn: "978-0142407332",
    },
    {
        title: "Wuthering Heights",
        author: "Emily Brontë",
        description: "A Gothic novel about the tumultuous relationship between Catherine Earnshaw and Heathcliff.",
        publishedDate: new Date("1847-12-01"),
        genre: ["Gothic", "Classic"],
        rating: 4.4,
        coverImageUrl: "https://example.com/wuthering-heights.jpg",
        isbn: "978-0141439556",
    },
    {
        title: "A Game of Thrones",
        author: "George R.R. Martin",
        description: "A fantasy novel that begins the epic series 'A Song of Ice and Fire,' set in the fictional world of Westeros.",
        publishedDate: new Date("1996-08-06"),
        genre: ["Fantasy", "Adventure"],
        rating: 4.8,
        coverImageUrl: "https://example.com/a-game-of-thrones.jpg",
        isbn: "978-0553103540",
    },
    {
        title: "Gone Girl",
        author: "Gillian Flynn",
        description: "A thriller about a woman who goes missing and the subsequent investigation into her disappearance.",
        publishedDate: new Date("2012-06-05"),
        genre: ["Thriller", "Mystery"],
        rating: 4.3,
        coverImageUrl: "https://example.com/gone-girl.jpg",
        isbn: "978-0307588371",
    },
    {
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        description: "A novel about a man who remains youthful while a portrait of him ages and reflects his moral corruption.",
        publishedDate: new Date("1890-07-01"),
        genre: ["Philosophy", "Classic"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-picture-of-dorian-gray.jpg",
        isbn: "978-0141439572",
    },
    {
        title: "The Bell Jar",
        author: "Sylvia Plath",
        description: "A semi-autobiographical novel about a young woman’s struggle with mental illness.",
        publishedDate: new Date("1963-01-01"),
        genre: ["Fiction", "Classic"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-bell-jar.jpg",
        isbn: "978-0060837024",
    },
    {
        title: "The Secret Garden",
        author: "Frances Hodgson Burnett",
        description: "A children’s novel about a young girl who discovers a hidden garden and transforms it, along with her own life.",
        publishedDate: new Date("1911-08-01"),
        genre: ["Children", "Classic"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-secret-garden.jpg",
        isbn: "978-0147514027",
    },
    {
        title: "The Giver",
        author: "Lois Lowry",
        description: "A dystopian novel about a boy chosen to inherit the role of Receiver of Memory in a seemingly perfect society.",
        publishedDate: new Date("1993-04-26"),
        genre: ["Dystopian", "Young Adult"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-giver.jpg",
        isbn: "978-0544336261",
    },
    {
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        description: "A dystopian novel set in a theocratic society where women are subjugated and used for reproduction.",
        publishedDate: new Date("1985-09-01"),
        genre: ["Dystopian", "Science Fiction"],
        rating: 4.7,
        coverImageUrl: "https://example.com/the-handmaids-tale.jpg",
        isbn: "978-0385490818",
    },
    {
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        description: "A self-help book that emphasizes the importance of focusing on what truly matters.",
        publishedDate: new Date("2016-09-13"),
        genre: ["Self-Help", "Non-Fiction"],
        rating: 4.3,
        coverImageUrl: "https://example.com/the-subtle-art-of-not-giving-a-fuck.jpg",
        isbn: "978-0062457714",
    },
    {
        title: "Educated",
        author: "Tara Westover",
        description: "A memoir about a woman who grows up in a strict and abusive household in rural Idaho but eventually escapes to learn about the wider world.",
        publishedDate: new Date("2018-02-20"),
        genre: ["Memoir", "Non-Fiction"],
        rating: 4.7,
        coverImageUrl: "https://example.com/educated.jpg",
        isbn: "978-0399590504",
    },
    {
        title: "Where the Crawdads Sing",
        author: "Delia Owens",
        description: "A novel about a young girl who grows up in the marshes of North Carolina and becomes a suspect in a murder case.",
        publishedDate: new Date("2018-08-14"),
        genre: ["Mystery", "Drama"],
        rating: 4.6,
        coverImageUrl: "https://example.com/where-the-crawdads-sing.jpg",
        isbn: "978-0735219090",
    },
    {
        title: "The Goldfinch",
        author: "Donna Tartt",
        description: "A Pulitzer Prize-winning novel about a boy who survives an explosion at a museum and becomes entangled in the world of art forgery.",
        publishedDate: new Date("2013-10-22"),
        genre: ["Literary Fiction", "Drama"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-goldfinch.jpg",
        isbn: "978-0316055437",
    },
    {
        title: "The Da Vinci Code",
        author: "Dan Brown",
        description: "A thriller involving a murder in the Louvre and a conspiracy related to the secret of the Holy Grail.",
        publishedDate: new Date("2003-03-18"),
        genre: ["Thriller", "Mystery"],
        rating: 4.3,
        coverImageUrl: "https://example.com/the-da-vinci-code.jpg",
        isbn: "978-0307474278",
    },
    {
        title: "The Brief Wondrous Life of Oscar Wao",
        author: "Junot Díaz",
        description: "A novel about a Dominican-American man’s cursed family and their struggles with dictatorship and immigration.",
        publishedDate: new Date("2007-09-04"),
        genre: ["Literary Fiction", "Historical"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-brief-wondrous-life-of-oscar-wao.jpg",
        isbn: "978-1594483295",
    },
    {
        title: "American Gods",
        author: "Neil Gaiman",
        description: "A novel that blends mythology with modern American culture, focusing on the conflict between old gods and new gods.",
        publishedDate: new Date("2001-06-19"),
        genre: ["Fantasy", "Mythology"],
        rating: 4.6,
        coverImageUrl: "https://example.com/american-gods.jpg",
        isbn: "978-0380789030",
    },
    {
        title: "The Road",
        author: "Cormac McCarthy",
        description: "A post-apocalyptic novel about a father and son journeying across a desolate landscape.",
        publishedDate: new Date("2006-09-26"),
        genre: ["Post-Apocalyptic", "Drama"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-road.jpg",
        isbn: "978-0307387899",
    },
    {
        title: "The Joy of Cooking",
        author: "Irma S. Rombauer",
        description: "A classic cookbook that has been a staple in American kitchens for decades.",
        publishedDate: new Date("1931-01-01"),
        genre: ["Cookbook", "Non-Fiction"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-joy-of-cooking.jpg",
        isbn: "978-0743246262",
    },
    {
        title: "The Diary of a Young Girl",
        author: "Anne Frank",
        description: "The diary of Anne Frank, a Jewish teenager hiding from the Nazis during World War II.",
        publishedDate: new Date("1947-06-25"),
        genre: ["Memoir", "Historical"],
        rating: 4.7,
        coverImageUrl: "https://example.com/the-diary-of-a-young-girl.jpg",
        isbn: "978-0553296983",
    },
    {
        title: "Life of Pi",
        author: "Yann Martel",
        description: "A novel about a boy stranded on a lifeboat with a Bengal tiger and his struggle for survival.",
        publishedDate: new Date("2001-09-11"),
        genre: ["Adventure", "Fiction"],
        rating: 4.6,
        coverImageUrl: "https://example.com/life-of-pi.jpg",
        isbn: "978-0156027328",
    },
    {
        title: "The Lovely Bones",
        author: "Alice Sebold",
        description: "A novel about a young girl who watches from the afterlife as her family copes with her murder.",
        publishedDate: new Date("2002-06-17"),
        genre: ["Fiction", "Mystery"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-lovely-bones.jpg",
        isbn: "978-0316334754",
    },
    {
        title: "The Immortal Life of Henrietta Lacks",
        author: "Rebecca Skloot",
        description: "A non-fiction book about Henrietta Lacks, whose cancer cells were used for medical research without her knowledge.",
        publishedDate: new Date("2010-02-02"),
        genre: ["Non-Fiction", "Biography"],
        rating: 4.8,
        coverImageUrl: "https://example.com/the-immortal-life-of-henrietta-lacks.jpg",
        isbn: "978-1400052189",
    },
    {
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        description: "A book exploring the history of humankind, from the emergence of Homo sapiens to modern society.",
        publishedDate: new Date("2011-09-04"),
        genre: ["Non-Fiction", "History"],
        rating: 4.7,
        coverImageUrl: "https://example.com/sapiens.jpg",
        isbn: "978-0062316097",
    },
    {
        title: "The Color Purple",
        author: "Alice Walker",
        description: "A novel about the life and struggles of African-American women in the early 20th century American South.",
        publishedDate: new Date("1982-05-29"),
        genre: ["Fiction", "Classic"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-color-purple.jpg",
        isbn: "978-0156028356",
    },
    {
        title: "The Kite Runner",
        author: "Khaled Hosseini",
        description: "A novel about the complicated friendship between two boys in Afghanistan and the impact of historical events on their lives.",
        publishedDate: new Date("2003-05-29"),
        genre: ["Fiction", "Drama"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-kite-runner.jpg",
        isbn: "978-1594480003",
    },
    {
        title: "The Silent Patient",
        author: "Alex Michaelides",
        description: "A psychological thriller about a woman who shoots her husband and then becomes mute, and the therapist who tries to uncover the truth.",
        publishedDate: new Date("2019-02-05"),
        genre: ["Thriller", "Mystery"],
        rating: 4.3,
        coverImageUrl: "https://example.com/the-silent-patient.jpg",
        isbn: "978-1250301697",
    },
    {
        title: "The Woman in the Window",
        author: "A.J. Finn",
        description: "A psychological thriller about a woman who believes she has witnessed a crime in her neighbor’s house.",
        publishedDate: new Date("2018-01-02"),
        genre: ["Thriller", "Mystery"],
        rating: 4.2,
        coverImageUrl: "https://example.com/the-woman-in-the-window.jpg",
        isbn: "978-0062678416",
    },
    {
        title: "The Night Circus",
        author: "Erin Morgenstern",
        description: "A fantasy novel about a magical competition between two young illusionists set in an enchanting circus.",
        publishedDate: new Date("2011-09-13"),
        genre: ["Fantasy", "Romance"],
        rating: 4.5,
        coverImageUrl: "https://example.com/the-night-circus.jpg",
        isbn: "978-0385534635",
    },
    {
        title: "Big Little Lies",
        author: "Liane Moriarty",
        description: "A novel that delves into the lives of three women, unraveling the secrets behind a murder.",
        publishedDate: new Date("2014-07-29"),
        genre: ["Fiction", "Mystery"],
        rating: 4.4,
        coverImageUrl: "https://example.com/big-little-lies.jpg",
        isbn: "978-0399167065",
    },
    {
        title: "The Sun and Her Flowers",
        author: "Rupi Kaur",
        description: "A collection of poetry and illustrations exploring themes of love, loss, and self-discovery.",
        publishedDate: new Date("2017-10-03"),
        genre: ["Poetry", "Non-Fiction"],
        rating: 4.7,
        coverImageUrl: "https://example.com/the-sun-and-her-flowers.jpg",
        isbn: "978-1449486792",
    },
    {
        title: "Circe",
        author: "Madeline Miller",
        description: "A retelling of the story of Circe, a powerful enchantress from Greek mythology.",
        publishedDate: new Date("2018-04-10"),
        genre: ["Fantasy", "Mythology"],
        rating: 4.6,
        coverImageUrl: "https://example.com/circe.jpg",
        isbn: "978-0316334754",
    },
    {
        title: "Red, White & Royal Blue",
        author: "Casey McQuiston",
        description: "A romantic comedy about the son of the U.S. president and a British prince who fall in love.",
        publishedDate: new Date("2019-05-14"),
        genre: ["Romance", "Contemporary"],
        rating: 4.7,
        coverImageUrl: "https://example.com/red-white-royal-blue.jpg",
        isbn: "978-1250316774",
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        description: "A science fiction epic set in a desert world, focusing on politics, religion, and the struggle for control of a valuable spice.",
        publishedDate: new Date("1965-08-01"),
        genre: ["Science Fiction", "Adventure"],
        rating: 4.8,
        coverImageUrl: "https://example.com/dune.jpg",
        isbn: "978-0441013593",
    },
    {
        title: "The Shadow of the Wind",
        author: "Carlos Ruiz Zafón",
        description: "A novel set in post-World War II Barcelona, involving a young boy who discovers a mysterious book.",
        publishedDate: new Date("2004-04-17"),
        genre: ["Mystery", "Literary Fiction"],
        rating: 4.6,
        coverImageUrl: "https://example.com/the-shadow-of-the-wind.jpg",
        isbn: "978-0143034902",
    },
    {
        title: "The Secret History",
        author: "Donna Tartt",
        description: "A thriller involving a group of students who become involved in murder and deception at an elite college.",
        publishedDate: new Date("1992-09-01"),
        genre: ["Thriller", "Mystery"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-secret-history.jpg",
        isbn: "978-0679417345",
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A classic novel set in the Roaring Twenties, exploring themes of wealth, class, and the American Dream.",
        publishedDate: new Date("1925-04-10"),
        genre: ["Classic", "Literary Fiction"],
        rating: 4.4,
        coverImageUrl: "https://example.com/the-great-gatsby.jpg",
        isbn: "978-0743273565",
    },
];

export default books;
